language: node_js
node_js:
- '0.11'
deploy:
  provider: heroku
  api_key:
    secure: Onfodsgwg05fHtFfaPH0qaYrkrKw8F1sQQtb7ZKUEaJPDa0k94HjYu1Ymdl+X/e9l2MzH/wJzySI4iUMtnvFUOiwNFRIpQiRm5nAtg7BsDagJJDetBhG7XXessv7ClvOCFr4qnJQr6TBfjdYnpQakkNNjrOjwFHuAEPIvwC5Yvg=
  app: coveohubot
  on:
    repo: Coveo/coveohubot
